- .github/workflows/black.yml
- .github/workflows/pypi-package-build-test.yml
- .github/workflows/pypi-release.yml
- CHANGELOG.md
- README.md
- fleetpings/app_settings.py
- fleetpings/templates/fleetpings/form/fleetDoctrine.html
- fleetpings/views.py
> [Issue #6] add a setting to use doctrine from fittings module if installed

- CHANGELOG.md
- fleetpings/admin.py
- fleetpings/form.py
Fleet type embed color is now a color picker in admin backend
> Fleet type color picker

- .coveragerc
- .editorconfig
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/automated-checks.yml
- .github/workflows/pypi-release.yml
- .gitignore
- CODEOWNERS
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Makefile
- README.md
- codecov.yml
- fleetpings/app_settings.py
- fleetpings/views.py
- runtests.py
- setup.py
- testauth/__init__.py
- testauth/celery.py
- testauth/settings.py
- testauth/urls.py
- testauth/wsgi.py
- tox.ini
> Adding test suite

- fleetpings/tests.py
- fleetpings/tests/test_access.py
- fleetpings/tests/test_installed_modules.py
- fleetpings/tests/utils.py
- testauth/settings.py
- tox.ini
> More tests

- .github/workflows/automated-checks.yml
- CHANGELOG.md
- fleetpings/__init__.py
- setup.py
- tox.ini
- Tests
- `allianceauth-app-utils` to replace built-in functions
- Minimum Python version set to 3.7
- Minimum AA version set to 2.8.8
> Push v2.6.0

- .github/workflows/automated-checks.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- fleetpings/__init__.py
- setup.py
- tox.ini
- Minimum requirements
- Python 3.7
- Alliance Auth v2.9.3
> Minimum requirements updated

- .pre-commit-config.yaml
- CHANGELOG.md
- Makefile
- fleetpings/__init__.py
- fleetpings/urls.py
- tox.ini
- Using `path` in URL config instead of soon-to-be removed `url`
> Next Version - v2.10.1

- CHANGELOG.md
- MANIFEST.in
- fleetpings/__init__.py
> Missing `helper` directory re-added

- fleetpings/views.py
Enables ordering for webhooks, when you have a few this helps with grouping them.
Fixes # (issue)
> Enable Ordering for the webhooks

- .pre-commit-config.yaml
- CHANGELOG.md
- fleetpings/__init__.py
- fleetpings/admin.py
- fleetpings/views.py
- Enable Ordering for the webhooks #89
> [RELEASE] v2.18.0

- CHANGELOG.md
- fleetpings/helper/ping_context.py
Fixing #127
- Discord Message Format Inconsistency (#127)
Fixes #127
> [FIX] Discord Message Format Inconsistency

- CHANGELOG.md
- pyproject.toml
- tox.ini
- Discord Message Format Inconsistency (#127)
Fixes #127
> [RELEASE] v2.24.1

- CHANGELOG.md
- fleetpings/templates/fleetpings/partials/ping/copy-paste-text.html
- pyproject.toml
> [RELEASE] v2.24.2

- CHANGELOG.md
- pyproject.toml
- Capitalization for translatable strings
- Use `clean_setting` function from `allianceauth´app-utils` instead of reinventing the
wheel and have our own
- Test suite updated
- Translation updates
> [RELEASE] v2.26.2

- fleetpings/helper/ping_context.py
- Remaining time to pre-pings
Closes #178
> [ADD] Remaining time to pre-pings

- CHANGELOG.md
- fleetpings/form.py
- fleetpings/helper/ping_context.py
- fleetpings/locale/cs/LC_MESSAGES/django.po
- fleetpings/locale/de/LC_MESSAGES/django.po
- fleetpings/locale/django.pot
- fleetpings/locale/es/LC_MESSAGES/django.po
- fleetpings/locale/fr_FR/LC_MESSAGES/django.po
- fleetpings/locale/it_IT/LC_MESSAGES/django.po
- fleetpings/locale/ja/LC_MESSAGES/django.po
- fleetpings/locale/ko_KR/LC_MESSAGES/django.po
- fleetpings/locale/nl/LC_MESSAGES/django.po
- fleetpings/locale/pl_PL/LC_MESSAGES/django.po
- fleetpings/locale/ru/LC_MESSAGES/django.po
- fleetpings/locale/sk/LC_MESSAGES/django.po
- fleetpings/locale/uk/LC_MESSAGES/django.po
- fleetpings/locale/zh_Hans/LC_MESSAGES/django.po
- fleetpings/templates/fleetpings/partials/form/form.html
- fleetpings/templates/fleetpings/partials/ping/copy-paste-text.html
- Field for the approximate fleet duration (Closes #183)
> [ADD] Field for approx. fleet duration

- .make/conf.d/django.mk
- CHANGELOG.md
- fleetpings/admin.py
- fleetpings/models.py
- Switch to `django-solo` to provide the singleton for the settings model, instead of the custom implementation
> [CHANGE] Switch to django-solo

- .make/conf.d/django.mk
- CHANGELOG.md
- fleetpings/constants.py
- fleetpings/helper/static_files.py
- fleetpings/templates/fleetpings/bundles/fleetpings-css.html
- fleetpings/templates/fleetpings/bundles/fleetpings-js.html
- fleetpings/templatetags/fleetpings.py
- fleetpings/tests/test_templatetags.py
- pyproject.toml
- Use `django-sri` for sri hashes
> [CHANGE] Use `django-sri` for sri hashes

- CHANGELOG.md
- fleetpings/constants.py
- fleetpings/helper/static_files.py
> [CHANGE] Better constant names

- CHANGELOG.md
- Makefile
- fleetpings/app_settings.py
- fleetpings/helper/static_files.py
- fleetpings/templatetags/fleetpings.py
- fleetpings/tests/test_app_settings.py
- fleetpings/tests/test_templatetags.py
> [CHANGE] Templatetag improved

- CHANGELOG.md
- fleetpings/form.py
- fleetpings/helper/ping_context.py
- fleetpings/locale/django.pot
- fleetpings/templates/fleetpings/partials/ping/copy-paste-text.html
- Spelling (It's EVE time, not Eve time)
> [FIX] Spelling (It's EVE time, not Eve time)

- CHANGELOG.md
- CONTRIBUTING.md
- fleetpings/models.py
> [ADD] Type hinting for managers

- CHANGELOG.md
- fleetpings/constants.py
- fleetpings/urls.py
> [ADD] Prefix for internal URLs

- CHANGELOG.md
- fleetpings/__init__.py
- fleetpings/constants.py
- fleetpings/helper/discord_webhook.py
- fleetpings/tests/test_dhooks.py
- Moved app related variables from `constants.py` to `__init__.py`
- Unused constants
> [CHANGE] Cleanup Constants

- CHANGELOG.md
- README.md
- fleetpings/__init__.py
- fleetpings/locale/django.pot
- Install and update instructions for Docker
- CSS cleanup
- Translations updated
- Unused template
> [RELEASE] v3.6.2

- .make/conf.d/development.mk
- .make/conf.d/django-esi.mk
- .make/conf.d/django.mk
- .make/conf.d/git.mk
- .make/conf.d/pre-commit.mk
- .make/conf.d/redis.mk
- .make/conf.d/tests.mk
- CHANGELOG.md
- Makefile
- README.md
- fleetpings/__init__.py
- fleetpings/locale/django.pot
- Switch to Terser for JavaScript compression
- Translations updated
> [RELEASE] v3.8.1

- CHANGELOG.md
- README.md
- fleetpings/__init__.py
> [RELEASE] v3.8.2
